### ISSUE TITLE
Потеря лога, в случае исключения при вызове метода "Соединение.ВызватьHTTPМетод"

### ISSUE THREAD

**Issue by ViktorErmakov** [ViktorErmakov/OneSniffer#4]
Коллеги, давайте подискутируем с подробными объяснениями, что лучше делать в этом случае.
Есть предложение делать запись в ЖР а потом доставать из ЖР данные и записывать в РС лог. Но это решение может при большом объеме ЖР на файловой базе повесить работу. При этом рассматривается делать отбор в ЖР с хранением даты последнего запроса, а так же события.
Понятное дело что если и делать такой функционал, то только опциональным, что бы его можно было выключить/ не включать.

для визуального представления: 
![image](https://github.com/ViktorErmakov/OneSniffer/assets/39617680/040d59a6-03ad-454c-89a3-10282d8e0b03)

**Comment by MikeFilimonov** [comment]
@ViktorErmakov, прошу уточнить, рассматриваем варианты использования стороннего хранения логов, скажем параллельную запись в ЖР и в стороннюю систему?

**Comment by ViktorErmakov** [comment]
> @ViktorErmakov, прошу уточнить, рассматриваем варианты использования стороннего хранения логов, скажем параллельную запись в ЖР и в стороннюю систему?

На данном этапе нет, пока работаем в 1С.

**Comment by MikeFilimonov** [comment]
> > @ViktorErmakov, прошу уточнить, рассматриваем варианты использования стороннего хранения логов, скажем параллельную запись в ЖР и в стороннюю систему?
> 
> На данном этапе нет, пока работаем в 1С.

Ок.
Кажется, пока в текущем варианте достаточно ЖР при условии контроля за его размерами. РС не нужен

**Comment by ViktorErmakov** [comment]
> > > @ViktorErmakov, прошу уточнить, рассматриваем варианты использования стороннего хранения логов, скажем параллельную запись в ЖР и в стороннюю систему?
> > 
> > 
> > На данном этапе нет, пока работаем в 1С.
> 
> Ок. Кажется, пока в текущем варианте достаточно ЖР при условии контроля за его размерами. РС не нужен

От РС я не готов совсем отказаться, это кажется не верно. В конечном виде записи логов должны быть в РС, и просматривать их надо из РС, не из ЖР напрямую. Из ЖР лишь можно считывать исключительные ситуации. Но нужно ли это вообще, ловить такие исключительные ситуации, и как их записывать, вот в чем изначальный вопрос.

**Comment by MikeFilimonov** [comment]
> > > > @ViktorErmakov, прошу уточнить, рассматриваем варианты использования стороннего хранения логов, скажем параллельную запись в ЖР и в стороннюю систему?
> > > 
> > > 
> > > На данном этапе нет, пока работаем в 1С.
> > 
> > 
> > Ок. Кажется, пока в текущем варианте достаточно ЖР при условии контроля за его размерами. РС не нужен
> 
> От РС я не готов совсем отказаться, это кажется не верно. В конечном виде записи логов должны быть в РС, и просматривать их надо из РС, не из ЖР напрямую. Из ЖР лишь можно считывать исключительные ситуации. Но нужно ли это вообще, ловить такие исключительные ситуации, и как их записывать, вот в чем изначальный вопрос.

Что именно неверно?
Какие задачи решает РС?
Какова актуальность данных логов в РС (как долго они там будут храниться)?
Кажется, его потенциал существенно ниже чем у ЖР, в части объемов и скорости записи.

**Comment by ViktorErmakov** [comment]
> Что именно неверно? Какие задачи решает РС? Какова актуальность данных логов в РС (как долго они там будут храниться)? Кажется, его потенциал существенно ниже чем у ЖР, в части объемов и скорости записи.

Цель этого расширения - быстрое чтение логов, я как разработчик подсистем использующих сторонние API ежедневно по многу раз смотрю эти логи, я конечно могу каждый раз читать из ЖР у меня база разработчика, вес ЖР не большой, но кому то это может сильно помешать, у кого ЖР весит очень много, поэтому любой функционал связанный с ЖР должен быть опциональным, а значит иметь замену. 
По поводу хранения логов ты сможешь ответить на этот вопрос запустив расширение и посмотрев настройки.
По моим задачам логи нужны за сегодня день разработки, и вчера это автотесты. Дальше двух дней никогда не искал ничего.
Скорость записи у РС не многим отличается от записи в ЖР, и не так важны миллисекунды, а вот скорость чтения отображения логов очень важна в решении подобных мне задач.
И давайте сильно не отходить в стороны от вопроса топика. РС использоваться будет.

**Comment by ViktorErmakov** [comment]
Еще раз поясню, выше метода "_ВызватьHTTPМетод" теоретически может быть открыта транзакция, поэтому в исключении мы даже если запишем логи, то они удаляться. Выражение "ВызватьИсключение" мы должны указать, что бы не было ошибок типа "в данной транзакции уже происходили ошибки". 
Можно в исключении проанализировать активна ли транзакция, если да, то записать в ЖР, и все же на форме логов по кнопке эти записи доставать, а если транзакция не активна, то писать в лог прям в исключении, тем самым покрыв логами максимальное количество обращений.
Тогда мы сохраняем быстрое чтение логов, и по желанию пользователя он может достать исключительные записи которые были в транзакции, такого сам еще не встречал, но покрыты будут все варианты.

**Comment by MikeFilimonov** [comment]
> > Что именно неверно? Какие задачи решает РС? Какова актуальность данных логов в РС (как долго они там будут храниться)? Кажется, его потенциал существенно ниже чем у ЖР, в части объемов и скорости записи.
> 
> Цель этого расширения - быстрое чтение логов, я как разработчик подсистем использующих сторонние API ежедневно по многу раз смотрю эти логи, я конечно могу каждый раз читать из ЖР у меня база разработчика, вес ЖР не большой, но кому то это может сильно помешать, у кого ЖР весит очень много, поэтому любой функционал связанный с ЖР должен быть опциональным, а значит иметь замену. По поводу хранения логов ты сможешь ответить на этот вопрос запустив расширение и посмотрев настройки. По моим задачам логи нужны за сегодня день разработки, и вчера это автотесты. Дальше двух дней никогда не искал ничего. Скорость записи у РС не многим отличается от записи в ЖР, и не так важны миллисекунды, а вот скорость чтения отображения логов очень важна в решении подобных мне задач. И давайте сильно не отходить в стороны от вопроса топика. РС использоваться будет.

Если данные только за два дня, РС подходит в первом приближении

**Comment by ViktorErmakov** [comment]
вот что я имел ввиду выше
![image](https://github.com/ViktorErmakov/OneSniffer/assets/39617680/72bc19e7-aa39-47cb-b37b-b2f78cb41727)

**Comment by ViktorErmakov** [comment]
Решено
